export interface CountryOption {
  code: string;
  name: string;
  currency?: string;
}

export const COUNTRIES: readonly CountryOption[] = [
  { code: "NG", name: "Nigeria", currency: "NGN" },
  { code: "US", name: "United States", currency: "USD" },
  { code: "GB", name: "United Kingdom", currency: "GBP" },
  { code: "KE", name: "Kenya", currency: "KES" },
  { code: "GH", name: "Ghana", currency: "GHS" },
  { code: "ZA", name: "South Africa", currency: "ZAR" },
  { code: "CA", name: "Canada", currency: "CAD" },
  { code: "AU", name: "Australia", currency: "AUD" },
  { code: "BR", name: "Brazil", currency: "BRL" },
  { code: "MX", name: "Mexico", currency: "MXN" },
  { code: "IN", name: "India", currency: "INR" },
  { code: "PH", name: "Philippines", currency: "PHP" },
  { code: "UG", name: "Uganda", currency: "UGX" },
  { code: "TZ", name: "Tanzania", currency: "TZS" },
  { code: "RW", name: "Rwanda", currency: "RWF" },
  { code: "DE", name: "Germany", currency: "EUR" },
  { code: "FR", name: "France", currency: "EUR" },
  { code: "ES", name: "Spain", currency: "EUR" },
  { code: "IT", name: "Italy", currency: "EUR" },
  { code: "NL", name: "Netherlands", currency: "EUR" },
  { code: "BE", name: "Belgium", currency: "EUR" },
  { code: "AT", name: "Austria", currency: "EUR" },
  { code: "PT", name: "Portugal", currency: "EUR" },
  { code: "IE", name: "Ireland", currency: "EUR" },
  { code: "FI", name: "Finland", currency: "EUR" },
  { code: "GR", name: "Greece", currency: "EUR" },
  { code: "EG", name: "Egypt", currency: "EGP" },
  { code: "AE", name: "United Arab Emirates", currency: "AED" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR" },
  { code: "SG", name: "Singapore", currency: "SGD" },
  { code: "JP", name: "Japan", currency: "JPY" },
  { code: "BH", name: "Bahrain", currency: "BHD" },
  { code: "KW", name: "Kuwait", currency: "KWD" },
  { code: "QA", name: "Qatar", currency: "QAR" },
  { code: "OM", name: "Oman", currency: "OMR" },
  { code: "TR", name: "Turkey", currency: "TRY" },
  { code: "AR", name: "Argentina", currency: "ARS" },
  { code: "CO", name: "Colombia", currency: "COP" },
  { code: "CL", name: "Chile", currency: "CLP" },
  { code: "PE", name: "Peru", currency: "PEN" },
  { code: "SN", name: "Senegal", currency: "XOF" },
  { code: "CI", name: "Ivory Coast", currency: "XOF" },
  { code: "CM", name: "Cameroon", currency: "XAF" },
] as const;

export const PAYOUT_RAILS = [
  { value: "bank_account", label: "Bank account" },
  { value: "mobile_money", label: "Mobile money" },
  { value: "paypal", label: "PayPal / Digital wallet" },
  { value: "cash_pickup", label: "Cash pickup" },
  { value: "card_transfer", label: "Debit/Credit Card" },
] as const;

export const FIAT_CURRENCIES = [
  { code: "NGN", name: "NGN — Nigerian naira" },
  { code: "USD", name: "USD — US dollar" },
  { code: "GBP", name: "GBP — British pound" },
  { code: "EUR", name: "EUR — Euro" },
  { code: "KES", name: "KES — Kenyan shilling" },
  { code: "GHS", name: "GHS — Ghanaian cedi" },
  { code: "ZAR", name: "ZAR — South African rand" },
  { code: "CAD", name: "CAD — Canadian dollar" },
  { code: "AUD", name: "AUD — Australian dollar" },
  { code: "BRL", name: "BRL — Brazilian real" },
  { code: "MXN", name: "MXN — Mexican peso" },
  { code: "INR", name: "INR — Indian rupee" },
  { code: "PHP", name: "PHP — Philippine peso" },
  { code: "UGX", name: "UGX — Ugandan shilling" },
  { code: "TZS", name: "TZS — Tanzanian shilling" },
  { code: "RWF", name: "RWF — Rwandan franc" },
  { code: "XOF", name: "XOF — CFA franc (BCEAO)" },
  { code: "XAF", name: "XAF — CFA franc (BEAC)" },
  { code: "EGP", name: "EGP — Egyptian pound" },
  { code: "AED", name: "AED — UAE dirham" },
  { code: "SAR", name: "SAR — Saudi riyal" },
  { code: "SGD", name: "SGD — Singapore dollar" },
  { code: "JPY", name: "JPY — Japanese yen" },
  { code: "BHD", name: "BHD — Bahraini dinar" },
  { code: "KW", name: "KWD — Kuwaiti dinar" },
  { code: "QAR", name: "QAR — Qatari riyal" },
  { code: "OMR", name: "OMR — Omani rial" },
  { code: "TRY", name: "TRY — Turkish lira" },
  { code: "ARS", name: "ARS — Argentine peso" },
  { code: "COP", name: "COP — Colombian peso" },
  { code: "CLP", name: "CLP — Chilean peso" },
  { code: "PEN", name: "PEN — Peruvian sol" },
] as const;
