name = "StellarTools Payments"
client_id = "c0177ec17c6e55668f70ba23d6912900"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "stellartools-testnet.myshopify.com"

[access_scopes]
scopes = ""


[auth]
redirect_urls = [
  "https://example.com/auth/callback",
  "https://example.com/auth/shopify/callback",
  "https://example.com/auth/login"
]

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"


[pos]
embedded = false
