name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Type-check & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build reusable packages
        run: |
          pnpm -w --filter @stellartools/core run build:prod
          pnpm -w --filter @stellartools/app-sdk run build
          pnpm -w --filter @stellartools/shared-ui run build
        env:
          STELLAR_TOOLS_BASE_URL: https://api.stellartools.com

      - name: Type-check
        run: pnpm --filter @stellartools/web type-check

      - name: Test
        run: pnpm --filter @stellartools/web test
